#!/usr/bin/env bash

scaffold_path="$DEV_LIB_PATH"/phpunit

if [[ ! -e phpunit.xml.dist ]]; then
	echo Symlinking phpunit.xml.dist...
	ln -s "${scaffold_path}"/module.xml.dist phpunit.xml.dist
else
	echo Not symlinking phpunit.xml.dist, already exists...
fi

if [[ ! -e phpunit.uninstall.xml.dist ]]; then
	echo Symlinking phpunit.uninstall.xml.dist...
	ln -s "${scaffold_path}"/phpunit.uninstall.xml.dist .
else
	echo Not symlinking phpunit.uninstall.xml.dist, already exists...
fi

if [[ ! -e tests/phpunit/tests ]]; then

	echo Creating tests/phpunit/tests directory...
	mkdir -p tests/phpunit/tests

	if [ ! -e tests/phpunit/tests/example.php ]; then
		echo Copying tests/phpunit/tests/example.php...
		cp "${scaffold_path}"/test.php tests/phpunit/tests/example.php
	fi

else
	echo Not creating tests/phpunit/tests directory, already exists...
fi

namespace=$(grep -oh "Namespace: .*" src/*.php)
namespace=${namespace#"Namespace: "}
namespace=${namespace##* }
lowercase_namespace=$(echo "$namespace" | tr '[:upper:]' '[:lower:]')

if [[ ! -e tests/phpunit/test-uninstall.php ]]; then

	echo Copying tests/phpunit/test-uninstall.php...
	cp "${scaffold_path}"/test-uninstall.php tests/phpunit/test-uninstall.php

	sed -i '' "s/My_Module/$namespace/" tests/phpunit/test-uninstall.php
	sed -i '' "s/mymodule/$lowercase_namespace/" tests/phpunit/test-uninstall.php

else
	echo Not copying tests/phpunit/test-uninstall.php, already exists...
fi

if [[ -z $WP_TESTS_DIR ]]; then

	while true; do

		if [[ -z $wp_tests_dir ]]; then
			echo "Please enter the full path to the WordPress tests directory (ex. /path/to/wordpress/tests/phpunit/):"
		fi

		read wp_tests_dir

		if [[ ! -d "$wp_tests_dir" ]]; then
			echo Directory "$wp_tests_dir" not found. Please enter a valid path:
		else
			break;
		fi

	done

	echo Adding definition of WP_TESTS_DIR var to ~/.bash_profile...
	echo "export WP_TESTS_DIR='${wp_tests_dir}'" >> ~/.bash_profile

	export WP_TESTS_DIR="$wp_tests_dir"

else
	echo Detected WordPress tests directory path "$WP_TESTS_DIR"
fi

wordpoints_modules_dir="${WP_TESTS_DIR%/tests/phpunit/}"/src/wp-content/wordpoints-modules
module_dir=${lowercase_namespace//_/-}

if [[ ! -e "$wordpoints_modules_dir/$module_dir" ]]; then
	echo Symlinking module to the WordPress tests modules directory...
	ln -s "$PWD"/src "$wordpoints_modules_dir/$module_dir"
else
	echo Not symlinking module, already exists in WordPress tests module directory...
fi

echo
echo Done!
echo
echo You can now run your phpunit tests with the command:
echo
echo phpunit
echo
echo You can run the uninstall tests with the command:
echo
echo phpunit -c phpunit.uninstall.xml.dist
echo
echo Your general tests will be placed in the tests/phpunit/tests directory.
echo You will find an example test case in tests/phpunit/tests/example.php
echo
echo Your uninstall test case is in tests/phpunit/test-uninstall.php
echo You can modify it to match your module.
echo

# EOF
